CIRCUIT_LAPS = {
    "Abu Dhabi Grand Prix": 58,
    "Australian Grand Prix": 57,
    "Austrian Grand Prix": 71,
    "Azerbaijan Grand Prix": 51,
    "Bahrain Grand Prix": 57,
    "Belgian Grand Prix": 44,
    "British Grand Prix": 52,
    "Canadian Grand Prix": 70,
    "Chinese Grand Prix": 56,
    "Dutch Grand Prix": 72,
    "Emilia Romagna Grand Prix": 63,
    "Hungarian Grand Prix": 70,
    "Italian Grand Prix": 53,
    "Japanese Grand Prix": 53,
    "Las Vegas Grand Prix": 50,
    "Mexico City Grand Prix": 71,
    "Miami Grand Prix": 57,
    "Monaco Grand Prix": 78,
    "Qatar Grand Prix": 57,
    "Saudi Arabian Grand Prix": 50,
    "Singapore Grand Prix": 62,
    "Spanish Grand Prix": 66,
    "São Paulo Grand Prix": 71,
    "United States Grand Prix": 56,
}

DRIVER_NAMES = {
    "NOR": "Lando Norris",
    "PIA": "Oscar Piastri",
    "VER": "Max Verstappen",
    "RUS": "George Russell",
    "LEC": "Charles Leclerc",
    "ANT": "Kimi Antonelli",
    "HAM": "Lewis Hamilton",
    "SAI": "Carlos Sainz",
    "HAD": "Isack Hadjar",
    "LAW": "Liam Lawson",
    "OCO": "Esteban Ocon",
    "COL": "Franco Colapinto",
    "STR": "Lance Stroll",
    "BOR": "Gabriel Bortoleto",
    "HUL": "Nico Hulkenberg",
    "ALO": "Fernando Alonso",
    "ALB": "Alexander Albon",
    "BEA": "Oliver Bearman",
    "TSU": "Yuki Tsunoda",
    "GAS": "Pierre Gasly",
}

COMPOUND_COLORS = {
    "SOFT":         "#E8002D",
    "MEDIUM":       "#FFF200",
    "HARD":         "#C8C8C8",
    "INTERMEDIATE": "#39B54A",
    "WET":          "#0067FF",
}

TEAM_COLORS = {
    "McLaren":        "#FF8000",
    "Red Bull Racing":"#3671C6",
    "Ferrari":        "#E8002D",
    "Mercedes":       "#27F4D2",
    "Aston Martin":   "#229971",
    "Alpine":         "#FF87BC",
    "Williams":       "#64C4FF",
    "Racing Bulls":   "#6692FF",
    "RB":             "#6692FF",
    "Kick Sauber":    "#52E252",
    "Haas F1 Team":   "#B6BABD",
    "AlphaTauri":     "#4E7C9B",
    "Alfa Romeo":     "#B12335",
}

STOP_COLORS = {1: "#2ECC71", 2: "#F39C12", 3: "#E74C3C"}
